spring:
  datasource:
    url : ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    open-in-view : false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        hbm2ddl:
          auto: update

  h2:
    console:
      enabled: false  # H2 Console 비활성화

    defer-datasource-initialization: true
